version: "3.8"
services:
  easy68kv2-web:
    container_name: easy68kv2-web
    build:
      context: ./caddy
      dockerfile: Dockerfile

    image: scirelli/easy68kv2-caddy
    ports:
      - "8080:8080"
    networks:
      - easy68k-net
    restart: always
    volumes:
      - "easy68kv2-data:/data"
    labels:
      org.cirelli.easy68kv2.web: "EASy68Kv2-Web"
    environment:
      - APP_USERNAME=cirelli
      - APP_PASSWORD_HASH=JDJhJDEwJHRKRE9HQllDR3F3S29PVUZmek9RNnVncGRIelJhSnhvbnFSVHphYlBNN20zQUNtV3ZacWw2

  easy68kv2-app:
    container_name: easy68kv2-app
    image: scirelli/easy68kv2-app
    restart: always
    volumes:
      - easy68kv2-data:/data
      - "${SRC_DIR}:/mnt/Projects"
    networks:
      - easy68k-net
    labels:
      org.cirelli.easy68kv2.app: "EASy68Kv2-App"

networks:
  easy68k-net:

volumes:
  easy68kv2-data:
