version: "3.8"
services:
  easy68kv2-web:
    container_name: easy68kv2-web
    build:
      context: ./caddy
      dockerfile: Dockerfile

    image: scirelli/easy68kv2-caddy
    ports:
      - "8080:8080"
    networks:
      - easy68k-net
    volumes:
      - "easy68kv2-data:/data"
    labels:
      org.cirelli.easy68kv2.web: "EASy68Kv2-Web"
    environment:
      - APP_USERNAME="cirelli"
      - APP_PASSWORD_HASH="JDJhJDEwJHNoVHNma0JDbVRpcE8wcjZob3hjcU85T1U1aG5yN3lSbC9VM1dOZkV1bGNiczVFeVBZbi9H"

  easy68kv2-app:
    container_name: easy68kv2-app
    image: scirelli/easy68kv2-app
    volumes:
      - easy68kv2-data:/data
      - "${SRC_DIR}:/mnt/Projects"
    networks:
      - easy68k-net
    labels:
      org.cirelli.easy68kv2.app: "EASy68Kv2-App"

networks:
  easy68k-net:

volumes:
  easy68kv2-data:
